### PR TITLE
Enhancement to support loading template in multiple thread

### PR DESCRIPTION
**Pull request by leonlee**
PR for issue #194

### CODE REVIEW

**Comment by leonlee** [comment]
PR for issue #194

**Comment by parrt** [comment]
Can you sign the contributors.txt file @leonlee ?

**Comment by parrt** [comment]
Hi. can you sign the contributors.txt file @leonlee ?

**Comment by leonlee** [comment]
hi parrt, i have signed, thx
but it looks testRendererForGroup was broken on my env.
java version "1.8.0_112"

**Comment by parrt** [comment]
@leonlee yep, Apparently Java 9 or 10 changed the formatting.  I just push some changes to allow it to test properly on both.

**Pull request merged**
