### PR TITLE
More .editorconfig

### PR DESCRIPTION
**Pull request by Clashsoft**
Adds additional IntelliJ-specific rules to .editorconfig.

### CODE REVIEW

**Comment by parrt** [comment]
Do these conform to the ST4 coding style?

**Comment by Clashsoft** [comment]
Yes! In fact, that's the point: with these rules, its easier (for IntelliJ users like me, at least) to make PRs that involve some kind of auto-generated code (like the getters in #240). It now automatically adheres to the code style.

**Comment by parrt** [comment]
Ok,sounds like now we're at a point I can cut a release. Sound right?

**Comment by Clashsoft** [comment]
Its probably ok, so the ANTLR release isn't delayed. Maybe #240 can be targeted for the next release?

**Comment by parrt** [comment]
ok, let me think about that. I hesitate to make widespread changes these days.  I'll see if ST4 still works for antlr ;)

**Pull request merged**
